from typing import Any

from fpdf import FPDF


def _pdf_to_bytes(pdf: FPDF) -> bytes:
    raw_output: Any = pdf.output(dest="S")
    if isinstance(raw_output, (bytes, bytearray)):
        return bytes(raw_output)
    return str(raw_output).encode("latin-1")


def build_resume_pdf(portfolio: dict[str, Any], username: str) -> bytes:
    user: dict[str, Any] = portfolio["user"]
    top_projects: list[dict[str, Any]] = portfolio["projects"]
    tech_stack: list[str] = portfolio.get("tech_stack", [])
    prof_summary: str = portfolio.get("professional_summary", "")

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_margins(left=15, top=15, right=15)

    name = str(user.get("name") or username)
    github_url = str(user.get("github_url") or f"https://github.com/{username}")
    location = str(user.get("location") or "Location not specified")

    pdf.set_text_color(20, 20, 20)
    pdf.set_font("Helvetica", "B", 24)
    pdf.cell(0, 12, name, new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 6, f"{github_url}  |  {location}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(4)

    if prof_summary:
        pdf.set_draw_color(0, 102, 204)
        pdf.set_line_width(0.5)
        pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
        pdf.ln(4)
        pdf.set_text_color(35, 35, 35)
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 7, "Professional Summary", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(60, 60, 60)
        pdf.multi_cell(0, 6, prof_summary)
        pdf.ln(3)

    if tech_stack:
        pdf.set_draw_color(200, 200, 200)
        pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
        pdf.ln(4)
        pdf.set_text_color(35, 35, 35)
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 7, "Core Technical Skills", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(60, 60, 60)
        pdf.multi_cell(0, 6, ", ".join(tech_stack[:15]))
        pdf.ln(3)

    pdf.set_draw_color(200, 200, 200)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(4)
    pdf.set_text_color(35, 35, 35)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "Selected Technical Projects", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)

    for project in top_projects:
        title = str(project.get("title") or "Untitled Project")
        language = str(project.get("language") or "Unknown")
        ai_description = " ".join(str(project.get("ai_description") or "").split())
        stars = int(project.get("stars") or 0)
        project_url = str(project.get("url") or "")

        pdf.set_text_color(20, 20, 20)
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(pdf.w - pdf.l_margin - pdf.r_margin - 40, 7, title)
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(40, 7, f"[{language}]", align="R", new_x="LMARGIN", new_y="NEXT")

        pdf.set_text_color(120, 120, 120)
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(0, 5, f"Stars: {stars}  |  {project_url}", new_x="LMARGIN", new_y="NEXT")

        pdf.set_text_color(50, 50, 50)
        pdf.set_font("Helvetica", "", 11)
        pdf.set_x(pdf.l_margin + 3)
        pdf.multi_cell(0, 6, f"- {ai_description}")
        pdf.ln(2.5)

    pdf.set_y(-20)
    pdf.set_draw_color(230, 230, 230)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(2)
    pdf.set_text_color(150, 150, 150)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 5, "Generated by TalentForge AI Resume Engine", align="C")

    return _pdf_to_bytes(pdf)


def build_simple_pdf(username: str, classification: str, text_content: str) -> bytes:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_margins(left=15, top=15, right=15)

    pdf.set_font("Helvetica", "B", 24)
    pdf.cell(0, 12, username, new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "I", 12)
    pdf.cell(0, 10, classification, new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)

    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 6, text_content.encode("latin-1", "replace").decode("latin-1"))

    return _pdf_to_bytes(pdf)

